function plotWeightedCentroid(track)
% Enter a specific track (i.e. track(#)) whose weighted centroids you wish
% to see.
all1 = track.WeightedCentroid(:,1:2:end);
all2 = track.WeightedCentroid(:,2:2:end);
% 
plot(all1(1),all2(1),'-o',...
    'LineWidth',0.5,...
    'MarkerSize',5,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','b')
plot(all1(end),all2(end),'-o',...
    'LineWidth',0.5,...
    'MarkerSize',5,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','r')
p = plot(all1(:),all2(:),'k','LineWidth',1);
% % modified jet-colormap
% n = length(all1(:));
% cd = [uint8(parula(n)*255) uint8(ones(n,1))].';
% 
% drawnow
% set(p.Edge, 'ColorBinding','interpolated', 'ColorData',cd)
end